src/sane_fin_site/fin_storage/urls.py
from django.urls import path, register_converter
from django.views.i18n import JavaScriptCatalog

from . import converters
from .views import (
    exporters_list, exporter_edit, exporter_detail, exporter_add, import_settings, api, sources_actuality)

register_converter(converters.IsoDateConverter, 'iso_date')
register_converter(converters.ComposeTypeConverter, 'compose_type')

app_name = 'fin_storage'

urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(packages=['django.contrib.admin']), name='jsi18n'),
    path('', exporters_list.ExportersView.as_view(), name='home'),
    path('exporters/', exporters_list.ExportersView.as_view(), name='exporters'),
    path('exporters/import/', import_settings.ImportSettingsView.as_view(), name='import_settings'),
    path('exporters/add/', exporter_add.ExportersAddView.as_view(), name='exporters_add'),
    path('exporters/add/type<int:type_id>/<uuid:rand_id>/info/',
         exporter_edit.ExportersAddTypedInfoView.as_view(),
         name='exporters_add_typed_info'),
    path('exporters/add/type<int:type_id>/<uuid:rand_id>/params/',
         exporter_edit.ExportersAddTypedParamsView.as_view(),
         name='exporters_add_typed_params'),
    path('exporters/add/type<int:type_id>/<uuid:rand_id>/cancel/',
         exporter_edit.ExportersAddTypedCancelView.as_view(),
         name='exporters_add_typed_cancel'),
    path('exporters/<int:id>/params/', exporter_edit.ExportersEditParamsView.as_view(), name='exporters_edit_params'),
    path('exporters/<int:id>/info/', exporter_edit.ExportersEditInfoView.as_view(), name='exporters_edit_info'),
    path('exporters/<int:id>/delete/', exporter_edit.ExportersDeleteView.as_view(), name='exporters_delete'),
    path('exporters/<int:id>/', exporter_detail.ExportersDetailView.as_view(), name='exporters_detail'),
    path('exporters/<int:id>/actualize/',
         sources_actuality.ActualizeHistoryRedirectView.as_view(),
         name='actualize_history'),
    path('sources_actuality/', sources_actuality.SourceApiActualityView.as_view(), name='sources_actuality'),
    path(r'api/v1/history/<str:code>/<iso_date:date_from>/<iso_date:date_to>/',
         api.JsonHistoryDataView.as_view(),
         name='api_history'),
    path(r'api/v1/compose/<str:code1>/<compose_type:compose_type>/<str:code2>/<iso_date:date_from>/<iso_date:date_to>/',
         api.JsonComposeDataView.as_view(),
         name='api_compose'),
]

src/sane_fin_site/sane_fin_site/urls.py
import re

from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path

from .views import static_handler

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fin_storage.urls')),
]

if settings.SERVE_STATIC:
    urlpatterns += [
        re_path(r'^%s(?P<path>.*)$' % re.escape(settings.STATIC_URL.lstrip('/')),
                static_handler, kwargs={'document_root': settings.STATIC_ROOT}),
    ]

src/sane_fin_site/fin_storage/views/api.py
import datetime
import decimal
import logging

from django.http import HttpResponseBadRequest, JsonResponse, HttpResponseNotFound
from django.utils import timezone
from django.views import generic
from sane_finances.sources import computing
from sane_finances.sources.base import InstrumentValue

from .. import db
from .. import models


class JsonHistoryDataView(generic.TemplateView):
    """
    Example:
        http://127.0.0.1:8000/api/v1/history/MSCI_World_NET_USD/2021-01-02/2021-08-01/?intraday=no&fill_gaps=no
    """
    intraday_query_param_name = 'intraday'
    fill_gaps_query_param_name = 'fill_gaps'

    date_format = '%Y-%m-%d'
    moment_format = '%Y-%m-%d %H:%M:%S'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.logger = logging.getLogger(__name__ + '.' + self.__class__.__name__)

    def render_to_response(self, context, **response_kwargs):
        exporter_code, date_from, date_to = self.kwargs['code'], self.kwargs['date_from'], self.kwargs['date_to']
        moment_from = datetime.datetime.combine(date_from, datetime.time.min, tzinfo=timezone.get_current_timezone())
        moment_to = datetime.datetime.combine(date_to, datetime.time.min, tzinfo=moment_from.tzinfo)

        intraday = str(self.request.GET.get(self.intraday_query_param_name, 'no')).lower()
        fill_gaps = str(self.request.GET.get(self.fill_gaps_query_param_name, 'no')).lower()

        self.logger.info(f"Try to get JSON instrument history data for {exporter_code!r} "
                         f"{date_from.isoformat()}..{date_to.isoformat()}, "
                         f"intraday={intraday!r}, fill_gaps={fill_gaps!r}")

        intraday = {'yes': True, 'no': False}.get(intraday, None)
        if intraday is None:
            self.logger.error("Bad intraday value")
            return HttpResponseBadRequest()

        fill_gaps = {'yes': True, 'no': False}.get(fill_gaps, None)
        if fill_gaps is None:
            self.logger.error("Bad fill_gaps value")
            return HttpResponseBadRequest()

        # noinspection PyUnresolvedReferences
        try:
            exporter = db.DatabaseContext().get_exporter_by_code(exporter_code)
        except models.Exporter.DoesNotExist:
            self.logger.warning(f"Exporter {exporter_code!r} not found")
            return HttpResponseNotFound()

        history_data = exporter.history_data

        data = []
        result = {
            'exporter_code': exporter.unique_code,
            'date_from': date_from.strftime(self.date_format),
            'date_to': date_to.strftime(self.date_format),
            'data': data
        }

        if date_from > date_to or not history_data:
            return JsonResponse(result)

        interval_data_type = (computing.IntervalHistoryDataValuesType.EVERY_DAY_VALUES
                              if fill_gaps
                              else computing.IntervalHistoryDataValuesType.ONLY_INTERIOR_VALUES)

        result_data = computing.build_sorted_history_data(
            history_data.values(),
            moment_from,
            moment_to,
            interval_data_type=interval_data_type,
            intraday=intraday)

        moment_format = self.moment_format if intraday else self.date_format

        data.extend([{'moment': moment.strftime(moment_format),
                      'value': value.value}
                     for moment, value
                     in result_data])

        return JsonResponse(result)


class JsonComposeDataView(generic.TemplateView):
    """
    Example:
        http://127.0.0.1:8000/api/v1/compose/MSCI_World_NET_USD/multiply/CBR.USD/2021-01-02/2021-08-01/?intraday=no&fill_gaps=no
    """
    intraday_query_param_name = 'intraday'
    fill_gaps_query_param_name = 'fill_gaps'

    date_format = '%Y-%m-%d'
    moment_format = '%Y-%m-%d %H:%M:%S'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.logger = logging.getLogger(__name__ + '.' + self.__class__.__name__)

    def render_to_response(self, context, **response_kwargs):
        exporter1_code, exporter2_code = self.kwargs['code1'], self.kwargs['code2']
        compose_type_string = self.kwargs['compose_type']
        date_from, date_to = self.kwargs['date_from'], self.kwargs['date_to']
        moment_from = datetime.datetime.combine(date_from, datetime.time.min, tzinfo=timezone.get_current_timezone())
        moment_to = datetime.datetime.combine(date_to, datetime.time.min, tzinfo=moment_from.tzinfo)

        intraday = str(self.request.GET.get(self.intraday_query_param_name, 'no')).lower()
        fill_gaps = str(self.request.GET.get(self.fill_gaps_query_param_name, 'no')).lower()

        self.logger.info(f"Try to get JSON composed history data "
                         f"for {exporter1_code!r} {compose_type_string} {exporter2_code!r}"
                         f"{date_from.isoformat()}..{date_to.isoformat()}, "
                         f"intraday={intraday!r}, fill_gaps={fill_gaps!r}")

        intraday = {'yes': True, 'no': False}.get(intraday, None)
        if intraday is None:
            self.logger.error("Bad intraday value")
            return HttpResponseBadRequest()

        fill_gaps = {'yes': True, 'no': False}.get(fill_gaps, None)
        if fill_gaps is None:
            self.logger.error("Bad fill_gaps value")
            return HttpResponseBadRequest()

        compose_type = computing.ComposeType(compose_type_string)

        # noinspection PyUnresolvedReferences
        try:
            exporter1 = db.DatabaseContext().get_exporter_by_code(exporter1_code)
        except models.Exporter.DoesNotExist:
            self.logger.warning(f"Exporter {exporter1_code!r} not found")
            return HttpResponseNotFound()
        # noinspection PyUnresolvedReferences
        try:
            exporter2 = db.DatabaseContext().get_exporter_by_code(exporter2_code)
        except models.Exporter.DoesNotExist:
            self.logger.warning(f"Exporter {exporter2_code!r} not found")
            return HttpResponseNotFound()

        data = []
        result = {
            'exporter1_code': exporter1.unique_code,
            'exporter2_code': exporter2.unique_code,
            'date_from': date_from.strftime(self.date_format),
            'date_to': date_to.strftime(self.date_format),
            'compose_type': compose_type_string,
            'data': data
        }
        if date_from > date_to:
            return JsonResponse(result)

        interval_data_type = (computing.IntervalHistoryDataValuesType.EVERY_DAY_VALUES
                              if fill_gaps
                              else computing.IntervalHistoryDataValuesType.ALLOW_PRECEDING_VALUE)

        # noinspection PyUnusedLocal
        def _return_stub_error_handler(
                ex: Exception,
                compose_operation_type: computing.ComposeType,
                moment: datetime.datetime,
                left_value: InstrumentValue,
                right_value: InstrumentValue) -> decimal.Decimal:
            error_stub_value = decimal.Decimal(0)
            return error_stub_value

        composed_data = computing.build_composed_sorted_history_data(
            exporter1.history_data.values(),
            exporter2.history_data.values(),
            compose_type,
            moment_from,
            moment_to,
            interval_data_type=interval_data_type,
            intraday=intraday,
            compose_error_handler=_return_stub_error_handler
        )

        moment_format = self.moment_format if intraday else self.date_format
        data.extend(({'moment': moment.strftime(moment_format),
                      'value': value}
                     for moment, value
                     in composed_data))

        return JsonResponse(result)

src/sane_fin_site/fin_storage/views/common.py
import datetime
import typing

from django import forms
from sane_finances.inspection import analyzers, serialize
from sane_finances.sources.base import DownloadParameterValuesStorage

from ..form_fields_managers import FormFieldsManager
from .. import __version__

T = typing.TypeVar('T')


def all_pages_context():
    return {
        'site_title': 'Sane Finances Storage',
        'site_header': 'Sane Finances Storage' + f" (v{__version__})",
        'site_url': '/',
        'has_permission': False,
        'is_popup': False,
        'is_nav_sidebar_enabled': False,
    }


def form_as_div(form: forms.BaseForm):
    # noinspection PyProtectedMember
    return form._html_output(
        normal_row='<div class="form-row field-%(field_name)s %(css_classes)s">%(errors)s'
                   '<div>%(label)s %(field)s%(help_text)s</div>'
                   '</div>',
        error_row='%s',
        row_ender='</div>',
        help_text_html=' <span class="helptext">%s</span>',
        errors_on_separate_row=False,
    )


def java_script_date_str(moment: datetime.date):
    return f"new Date({moment.year},{moment.month - 1},{moment.strftime('%d,%H,%M,%S')})"


class SpecificInstanceManagersPack:
    instance_builder: analyzers.InstanceBuilder
    factory_converter: analyzers.InstanceFactoryDataConverter
    instance_flattener: analyzers.InstanceFlattener
    form_fields_manager: FormFieldsManager
    serializer: serialize.FlattenedDataJsonSerializer

    def __init__(
            self,
            download_param_values_storage: DownloadParameterValuesStorage,
            root_data_class: typing.Type[T],
            root_factory: typing.Callable[..., T],
            attr_name_prefix: str):
        instance_analyzer = analyzers.FlattenedAnnotatedInstanceAnalyzer(
            root_data_class,
            download_param_values_storage,
            attr_name_prefix)
        self.factory_converter = analyzers.InstanceFactoryDataConverter(instance_analyzer)
        self.instance_flattener = analyzers.InstanceFlattener(instance_analyzer, download_param_values_storage)
        self.instance_builder = analyzers.InstanceBuilder(
            root_factory,
            download_param_values_storage)
        self.form_fields_manager = FormFieldsManager(
            instance_analyzer,
            download_param_values_storage)
        self.serializer = serialize.FlattenedDataJsonSerializer(instance_analyzer, download_param_values_storage)

src/sane_fin_site/fin_storage/views/exporter_add.py
import logging
import typing
import uuid

from django import forms
from django.forms import widgets
from django.forms.utils import ErrorList
from django.urls import reverse_lazy
from django.views import generic
from sane_finances.inspection import analyzers
from sane_finances.sources.base import InstrumentExporterRegistry

from .common import all_pages_context
from .. import apps
from ..cachers import StaticDataCache


class ExporterTypeForm(forms.Form):
    required_css_class = 'required'
    error_css_class = 'errors'

    exporter_type = forms.ChoiceField(widget=widgets.RadioSelect())

    class InstrumentExporterRegistryViewModel:
        def __init__(self, registry: InstrumentExporterRegistry):
            self._registry = registry

        @property
        def name(self):
            return self._registry.name

        @property
        def provider_site(self):
            return self._registry.provider_site

        @property
        def api_url(self):
            return self._registry.api_url

        @property
        def exporter_type(self):
            return analyzers.get_full_path(self._registry.factory.__class__)

    def __init__(self,
                 available_exporters_registries: typing.OrderedDict[int, InstrumentExporterRegistry],
                 instance=None,
                 data=None, files=None, auto_id='id_%s', prefix=None,
                 initial=None, error_class=ErrorList, label_suffix=None,
                 empty_permitted=False, field_order=None, use_required_attribute=None, renderer=None):
        super().__init__(data, files, auto_id, prefix,
                         initial, error_class, label_suffix,
                         empty_permitted, field_order, use_required_attribute, renderer)

        self.available_exporters_registries = available_exporters_registries
        self.instance = instance

        self.fields['exporter_type'].choices = [
            (str(registry_id), ExporterTypeForm.InstrumentExporterRegistryViewModel(registry))
            for registry_id, registry
            in available_exporters_registries.items()]

    @property
    def model_name(self):
        return 'exporter_type'

    def save(self):
        return self.instance


class ExportersAddView(generic.edit.CreateView):
    template_name = apps.FinStorageConfig.name + '/exporter_add.html'
    form_class = ExporterTypeForm

    title = 'Add new exporter'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.logger = logging.getLogger(__name__ + '.' + self.__class__.__name__)

        self.selected_type_id: typing.Optional[int] = None

    def get_success_url(self):
        return reverse_lazy(apps.FinStorageConfig.name + ':exporters_add_typed_info',
                            kwargs={'type_id': self.selected_type_id,
                                    'rand_id': uuid.uuid4()},
                            current_app=apps.FinStorageConfig.name)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data.update(
            {
                **all_pages_context(),
                'title': self.title,
                'subtitle': None
            })
        return context_data

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        available_exporters_registries = StaticDataCache().get_available_exporters_registries()

        self.logger.info(f"Got {len(available_exporters_registries)} available exporters registries")

        kwargs['available_exporters_registries'] = available_exporters_registries

        return kwargs

    def form_valid(self, form: forms.Form):
        self.selected_type_id = int(form.cleaned_data['exporter_type'])

        return super().form_valid(form)

src/sane_fin_site/fin_storage/templates/fin_storage/base.html
{% extends "admin/base.html" %}
{% load static %}

{% block title %}{{ title }} | {{ site_title }}{% endblock %}

{% block extrahead %}
    <meta charset="utf-8">
    {{ block.super }}

    <script src="{% url 'fin_storage:jsi18n' %}"></script>
    <script type="text/javascript" src="{% static '/admin/js/core.js' %}"></script>
{% endblock %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/changelists.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}">
{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'fin_storage:exporters' %}">{{ site_header }}</a></h1>
{% endblock %}

{% block nav-global %}
<div>
    <a href="{% url 'admin:index' %}">Admin Page</a>
</div>
{% endblock %}

{% block coltype %}{% endblock %}

src/sane_fin_site/fin_storage/templates/fin_storage/confirmation.html
{% extends "fin_storage/base.html" %}
{% load static %}

{% block extrahead %}
    {{ block.super }}
    <script src="{% static 'admin/js/cancel.js' %}" async></script>

    {{ form.media }}
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'fin_storage:exporters' %}">All Exporters</a>
    {% if object %}
    &rsaquo; <a href="{% url 'fin_storage:exporters_detail' object.id %}">{{ object.unique_code }}</a>
    {% endif %}
    {% if title %} &rsaquo; {{ title }}{% endif %}
</div>
{% endblock %}

{% block bodyclass %}{{ block.super }} delete-confirmation{% endblock %}

{% block content %}
    <p>{{ question }}</p>

    <form method="post">{% csrf_token %}
        <div>
            <input type="hidden" name="post" value="yes">
            <input type="submit" value="Yes, I’m sure">
            <a href="#" class="button cancel-link">No, take me back</a>
        </div>
    </form>
{% endblock %}

src/sane_fin_site/fin_storage/templates/fin_storage/exporter_edit.html
{% extends "fin_storage/base.html" %}
{% load static %}

{% block extrahead %}
    {{ block.super }}

    {{ form.media }}
{% endblock %}

{% block extrastyle %}
    {{ block.super }}
    <style>
        input {margin: 0;}
    </style>
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'fin_storage:exporters' %}">All Exporters</a>
    {% if new_exporter %}
    {# Create new exporter: #}
    &rsaquo; <a href="{% url 'fin_storage:exporters_add' %}">{{ title }}</a>
    &rsaquo; {{ object.exporter_registry.name|truncatewords:"18" }}
    {% else %}
    {# Edit existing exporter: #}
    &rsaquo; <a href="{% url 'fin_storage:exporters_detail' object.id %}">{{ object.unique_code }}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    {% endif %}
</div>
{% endblock %}

{% block bodyclass %}{{ block.super }} model-{{ form.model_name }} change-form{% endblock %}

{% block content %}
<div id="content-main">
    <form method="post" id="{{ form.model_name }}_form" novalidate>
        {% csrf_token %}

        <div>
        {% if form.errors %}
            <p class="errornote">
            {% if form.errors|length == 1 %}Please correct the error below.{% else %}Please correct the errors below.{% endif %}
            </p>
            {{ form.non_field_errors }}
        {% endif %}

        <fieldset class="module aligned ">
            {{ form.as_div_common }}
        </fieldset>

        <fieldset class="module aligned ">
            {% if find_instrument %}
            <h2>Parameters to find instruments:</h2>
            {% else %}
            <h2>Exporter's parameters for download:</h2>
            {% endif %}
            {{ form.as_div_specific }}
        </fieldset>

        {% if find_instrument %}
        <fieldset class="module aligned ">
            <h2>Enter instrument info manually:</h2>
            {{ form.as_div_manual }}
        </fieldset>
        {% endif %}

        <div class="submit-row">
            {% if find_instrument %}
            <input type="submit" value="Continue with manual info" class="default" name="_with_manual">
            <input type="submit" value="Find all" class="default" name="_find">
            {% else %}
            <input type="submit" value="Save" class="default" name="_save">
            <input type="submit" value="Select another instrument" name="_select_another" style="float: left">

            {% if can_cancel %}
            <a href="{% url 'fin_storage:exporters_add_typed_cancel' type_id rand_id %}"
               class="button default closelink"
               style="float: left">Cancel</a>
            {% endif %}

            {% endif %}
        </div>

        {% if find_instrument %}
        <fieldset class="module aligned ">
            <h2>Or select one of available instruments (click 'Find All' before):</h2>
            <div class="form-row field-instrument_info">
                {% if form.instrument_info.errors %}{{ form.instrument_info.errors }}{% endif %}

                <div class="module" id="changelist">
                    <div class="changelist-form-container">
                <div class="results">
                    <table id="result_list">
                        <thead>
                            <tr>
                                <th scope="col"><div class="text"><span>Code</span></div></th>
                                <th scope="col"><div class="text"><span>Name</span></div></th>
                                <th scope="col"><div class="text"><span>Provider specific name</span></div></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for instrument_info_provider in form.instrument_info %}
                            <tr>
                                <td>
                                    <!--suppress XmlInvalidId -->
                                    <label for="{{ instrument_info_provider.id_for_label }}"
                                    style="padding: 0;">
                                        {{ instrument_info_provider.tag }}
                                        {{ instrument_info_provider.choice_label.instrument_info.code }}
                                    </label>
                                </td>
                                <td style="vertical-align: middle;">{{ instrument_info_provider.choice_label.instrument_info.name }}</td>
                                <td style="vertical-align: middle;">{{ instrument_info_provider.choice_label }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                        <p class="paginator">{{ form.instrument_info|length }} found</p>
                        </div>
                </div>
            </div>
        </fieldset>

        <div class="submit-row">
            <input type="submit" value="Continue with found" class="default" name="_with_found">
            {% if can_cancel %}
            <a href="{% url 'fin_storage:exporters_add_typed_cancel' type_id rand_id %}"
               class="button default closelink"
               style="float: left">Cancel</a>
            {% endif %}
        </div>
        {% endif %}

        {% block admin_change_form_document_ready %}
            <script id="django-admin-form-add-constants"
                    src="{% static 'admin/js/change_form.js' %}"
                    data-model-name="{{ form.model_name }}"
                    async>
            </script>
        {% endblock %}

        </div>
    </form>
</div>
{% endblock %}

src/sane_fin_site/fin_storage/templates/fin_storage/exporters_list.html
{% extends "fin_storage/base.html" %}
{% load static %}

{% block extrahead %}
    {{ block.super }}
    <script type="text/javascript" src="{% static '/admin/js/actions.js' %}"></script>

    {{ action_form.media }}
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'fin_storage:exporters' %}">All Exporters</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
</div>
{% endblock %}

{% block content %}
  <div id="content-main">
    {% block object-tools %}
        <ul class="object-tools">
            <li><a href="{% url 'fin_storage:exporters_add' %}" class="addlink">Add exporter</a></li>
            <li><a href="{% url 'fin_storage:sources_actuality' %}" class="viewsitelink">Sources actuality</a></li>
            <li><a href="{% url 'fin_storage:import_settings' %}" class="viewsitelink">Import settings</a></li>
        </ul>
    {% endblock %}

    <div class="module" id="changelist">
      <div class="changelist-form-container">
        <form id="changelist-form" method="post" novalidate>{% csrf_token %}

        {% block result_list %}
            <div class="actions">
              {% block actions %}
                {% block actions-form %}
                {% for field in action_form %}{% if field.label %}<label>{{ field.label }} {% endif %}{{ field }}{% if field.label %}</label>{% endif %}{% endfor %}
                {% endblock %}
                {% block actions-submit %}
                <button type="submit" class="button" title="Run the selected action" name="index" value="0">Go</button>
                {% endblock %}
                {% block actions-counter %}
                <span class="action-counter" data-actions-icnt="{{ object_list|length }}">{{ selection_note }}</span>
                {% endblock %}
              {% endblock %}
            </div>

            <div class="results">
                <table id="result_list">
                    <thead>
                        <tr>
                            <th scope="col" class="action-checkbox-column">
                                <div class="text">
                                    <span>
                                        <input type="checkbox" id="action-toggle">
                                    </span>
                                </div>
                                <div class="clear"></div>
                            </th>
                            <th scope="col"><div class="text"><span>Code</span></div></th>
                            <th scope="col"><div class="text"><span>Description</span></div></th>
                            <th scope="col"><div class="text"><span>Data quality</span></div></th>
                            <th scope="col"><div class="text"><span>Type</span></div></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for exporter in object_list %}
                        <tr>
                            <td class="action-checkbox">
                                <input type="checkbox" name="{{ action_checkbox_name }}" value="{{ exporter.id }}" class="action-select">
                            </td>
                            <th>
                                <a href="{% url 'fin_storage:exporters_detail' exporter.id %}">{{ exporter.unique_code }}</a>
                            </th>
                            <td>{{ exporter.description }}</td>
                            <td>
                                {% if exporter.has_gaps or exporter.disabled or not exporter.is_actual or not exporter.is_active %}
                                    {% if exporter.disabled %}
                                    <ul class="errorlist">
                                    <li>{{ exporter.error_message|truncatechars:50 }}</li>
                                    </ul>
                                    {% elif exporter.is_active %}
                                        <ul class="errorlist">
                                        {% if exporter.has_gaps %}
                                        <li><a href="{% url 'fin_storage:exporters_detail' exporter.id %}">Fill the gaps</a></li>
                                        {% endif %}
                                        {% if not exporter.is_actual %}
                                        <li><a href="{% url 'fin_storage:actualize_history' exporter.id %}">Actualize</a></li>
                                        {% endif %}
                                        </ul>
                                    {% else %}
                                    <span>Inactive</span>
                                    {% endif %}
                                {% else %}
                                <span>Actual</span>
                                {% endif %}
                            </td>
                            <td>{{ exporter.exporter_type }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endblock %}

        {% block pagination %}<p class="paginator">{{ object_list|length }} found</p>{% endblock %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}